services:

  # app:
  #   build: ./app
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   restart: always
  #   environment:
  #     DATABASE_URL: "postgres://admin:Radhe%401234@postgres:5432/url_shortner"
  #     REDIS_URL: "redis://redis-cache:6379"

  postgres:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Radhe@1234
      POSTGRES_DB: url_shortner
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d url_shortner" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql

  migration:
    build: ./app
    command: npx node-pg-migrate up
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"
    environment:
      DATABASE_URL: "postgres://admin:Radhe%401234@postgres:5432/url_shortner"

  redis-cache:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data:
